### PR TITLE
Allow ECO file parse to fail

### PR DESCRIPTION
**Pull request by ddugovic**
I don't have `../../eco.json`.

### CODE REVIEW

**Comment by rpdelaney** [comment]
How did you install? It should be part of the package. You might have to initialize the submodule with something like `git submodule init ./python-chess/annotator/annotator/eco` I think

**Comment by ddugovic** [comment]
I installed via `git clone https://github.com/rpdelaney/python-chess-annotator.git ; cd python-chess-annotator`

**Comment by rpdelaney** [comment]
Oh, I just looked again. I structured this weirdly, and I don't remember why. Try `git submodule init ./python-chess-annotator/eco` and that should help for now?

I think of the eco submodule as part of the app, so I have mixed feelings about skipping it if it's not found. That feels like masking a bug in installation. It seems to me I need to rethink how I've packaged this.

**Comment by ddugovic** [comment]
```
lila@dugovic-host:~/python-chess-annotator$ git submodule init ./python-chess-annotator/eco
error: pathspec './python-chess-annotator/eco' did not match any file(s) known to git.
```

**Comment by ddugovic** [comment]
OK, I found the file now:

```
lila@dugovic-host:~$ rm python-chess-annotator/ -rf
lila@dugovic-host:~$ git clone https://github.com/rpdelaney/python-chess-annotator.git ; cd python-chess-annotator
Cloning into 'python-chess-annotator'...
remote: Counting objects: 821, done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 821 (delta 37), reused 71 (delta 37), pack-reused 745
Receiving objects: 100% (821/821), 147.56 KiB | 1.15 MiB/s, done.
Resolving deltas: 100% (480/480), done.
lila@dugovic-host:~/python-chess-annotator$ git submodule update
lila@dugovic-host:~/python-chess-annotator$ git submodule update --recursive
lila@dugovic-host:~/python-chess-annotator$ ls eco/
lila@dugovic-host:~/python-chess-annotator$ git submodule init
Submodule 'eco' (git@github.com:niklasf/eco.git) registered for path 'eco'
lila@dugovic-host:~/python-chess-annotator$ git submodule update --recursive
Cloning into '/home/lila/python-chess-annotator/eco'...
Enter passphrase for key '/home/lila/.ssh/id_rsa': 
Submodule path 'eco': checked out '8ef60f84461f885373bf4244ed908e7d8facb754'
```

**Pull request closed without merging**
